services:
  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:root@localhost:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"