services:
  db:
    image: postgres:17.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres-data: # Volume for persisting PostgreSQL data